### ISSUE TITLE
How to deblur RGB picture？

### ISSUE THREAD

**Issue by Akumio** [ayanc/ndeblur#4]
Excuse me,Can this project target color images and if so，how to deblur RGB picture?

**Comment by ayanc** [comment]
This paper describes a method to estimate the blur kernel, and then uses the EPLL algorithm to do the actual deblurring (non-blind deconvolution). Given color images, you should convert them to grayscale and use that for kernel estimation. Then, you can search for non-blind deconvolution methods for color images.
